keys:
  - users:
    - &paz age1khrvffglcrt27x49rk338a23pxmq7pavmmydfyj5sqpj3jglfe9se7vhkr
  - hosts:
    - &cradix age1tgkt3lw0enhr5lt82d3uhtsa8gwpkc66eecj2chrj8jp3z2zlf7st84jv7
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *paz
      - *cradix